// profile
export const OPEN_AVATAR_MENU = 'OPEN_AVATAR_MENU';
export const CLOSE_AVATAR_MENU = 'CLOSE_AVATAR_MENU';
export const CONFIRM_NEW_PASSWORD = 'CONFIRM_NEW_PASSWORD';
export const CHANGE_HELP_MESSAGE = 'CHANGE_HELP_MESSAGE';

// contactInfo
export const GET_CONTACT_INFO = 'GET_CONTACT_INFO';

//
export const CANCEL_FORWARD_MESSAGE = 'CANCEL_FORWARD_MESSAGE';

//
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const INIT = 'INIT';

// for all inputs
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CHANGE_PASSWORD_VISIBILITY = 'CHANGE_PASSWORD_VISIBILITY';

// Chats
export const DELETE_CHAT = 'DELETE_CHAT';

// Contacts
export const OPEN_CONTACT_INFO = 'OPEN_CONTACT_INFO';

// Popup
export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

// Settings
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const CANCEL_EDIT_PROFILE = 'CANCEL_EDIT_PROFILE';
//
export const OPEN_SEARCH = 'OPEN_SEARCH';
export const CLOSE_SEARCH = 'CLOSE_SEARCH';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
