// for all inputs
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
export const CHANGE_PASSWORD_VISIBILITY = 'CHANGE_PASSWORD_VISIBILITY';

// header
export const CHANGE_HEADER_VISIBILITY = 'CHANGE_HEADER_VISIBILITY';


// Chats
export const DELETE_CHAT = 'DELETE_CHAT';

// Contacts
export const OPEN_CONTACT_INFO = 'OPEN_CONTACT_INFO';

// Popup
export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';

// Settings
export const TOGGLE_EDIT_PROFILE_MODE = 'TOGGLE_EDIT_PROFILE_MODE';
export const TOGGLE_SETTINGS_NAV_ACTIVITY = 'TOGGLE_SETTINGS_NAV_ACTIVITY';
//
export const OPEN_SEARCH = 'OPEN_SEARCH';
export const CLOSE_SEARCH = 'CLOSE_SEARCH';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
