// export const LOGIN__CHANGE_INPUT = 'LOGIN__CHANGE_INPUT_VALUE';
// export const LOGIN__CHANGE_PASSWORD_VISIBILITY = 'LOGIN__CHANGE_PASSWORD_VISIBILITY';

export const LOGIN = 'LOGIN';

export const GO_TO_REGISTRATION_PAGE = 'GO_TO_REGISTRATION_PAGE';
